---
apiVersion: v1
kind: Namespace
metadata:
  name: melizarov
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZXh1cy1kb2NrLms4cy5wbGF5cGl0LmJ5OjgwIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6ImFkbWluIiwiYXV0aCI6IllXUnRhVzQ2WVdSdGFXND0ifX19
kind: Secret
metadata:
  name: docker-secret
  namespace: melizarov
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: melizarov
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: nexus-dock.k8s.playpit.by/helloworld-melizarov
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /helloworld-ws/
              port: 8080
              httpHeaders:
                - name: Server
                  value: openresty/1.15.8.2
            initialDelaySeconds: 24
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
      imagePullSecrets:
        - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: melizarov
  name: tomcat-svc
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  ports:
    - port: 80
      targetPort: 8080
      name: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: melizarov
  name: tomcat-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: melizarov.k8s.playpit.by
      http:
        paths:
          - path: /
            backend:
              serviceName: tomcat-svc
              servicePort: 80